[package]
name = "api-service"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../../shared/common" }
tokio = { workspace = true }
axum = { workspace = true }
serde_json = { workspace = true }
